#!/usr/bin/env python3
"""Sync danh sách bài free từ LeetCode GraphQL API.

Nguồn dữ liệu duy nhất (Single Source of Truth) cho metadata bài LeetCode.

Đầu ra:
  - leetcode/data/problems.json        : dataset canonical (3248 bài free)
  - leetcode/data/tags.json            : index tag chính thức kèm số bài
  - website/leetcode-problems.js       : bản JS cho website tĩnh (hỗ trợ file://)

Chạy lại bất cứ lúc nào để làm mới dữ liệu: python3 tools/sync_leetcode.py
"""

import json
import time
import urllib.request
from collections import Counter
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "leetcode" / "data"
WEBSITE_DIR = ROOT / "website"

API_URL = "https://leetcode.com/graphql"
PAGE_SIZE = 100

QUERY = """
query problemsetQuestionList($categorySlug: String, $limit: Int, $skip: Int, $filters: QuestionListFilterInput) {
  problemsetQuestionList: questionList(
    categorySlug: $categorySlug, limit: $limit, skip: $skip, filters: $filters
  ) {
    total: totalNum
    questions: data {
      questionFrontendId
      title
      titleSlug
      difficulty
      isPaidOnly
      topicTags { name slug }
    }
  }
}
"""


def fetch_page(skip: int) -> dict:
    body = json.dumps({
        "query": QUERY,
        "variables": {
            "categorySlug": "all-code-essentials",
            "limit": PAGE_SIZE,
            "skip": skip,
            "filters": {},
        },
    }).encode()
    request = urllib.request.Request(API_URL, data=body, headers={
        "Content-Type": "application/json",
        "Referer": "https://leetcode.com/problemset/",
        "User-Agent": "Mozilla/5.0 (Knowledge OS sync)",
    })
    with urllib.request.urlopen(request, timeout=30) as response:
        payload = json.load(response)
    return payload["data"]["problemsetQuestionList"]


def fetch_all_free() -> list:
    problems = []
    skip = 0
    total = None
    while True:
        page = fetch_page(skip)
        total = page["total"]
        questions = page["questions"]
        if not questions:
            break
        problems.extend(q for q in questions if not q["isPaidOnly"])
        skip += len(questions)
        print(f"  fetched {min(skip, total)}/{total} (free: {len(problems)})", flush=True)
        if skip >= total:
            break
        time.sleep(0.25)
    problems.sort(key=lambda q: int(q["questionFrontendId"]))
    return problems


def build_dataset(problems: list) -> dict:
    by_difficulty = Counter(p["difficulty"] for p in problems)
    return {
        "generatedAt": date.today().isoformat(),
        "source": "https://leetcode.com/graphql",
        "note": "Chỉ chứa bài free (isPaidOnly = false). Metadata only, không chứa nội dung bài học.",
        "totalFree": len(problems),
        "byDifficulty": {d: by_difficulty.get(d, 0) for d in ("Easy", "Medium", "Hard")},
        "problems": [
            {
                "id": int(p["questionFrontendId"]),
                "title": p["title"],
                "slug": p["titleSlug"],
                "difficulty": p["difficulty"],
                "topicTags": [t["slug"] for t in p["topicTags"]],
            }
            for p in problems
        ],
    }


def build_tag_index(problems: list) -> dict:
    counts = Counter()
    names = {}
    for p in problems:
        for tag in p["topicTags"]:
            counts[tag["slug"]] += 1
            names[tag["slug"]] = tag["name"]
    return {
        "generatedAt": date.today().isoformat(),
        "totalTags": len(counts),
        "tags": [
            {"slug": slug, "name": names[slug], "count": count}
            for slug, count in sorted(counts.items(), key=lambda item: (-item[1], item[0]))
        ],
    }


def main() -> None:
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    print("Fetching free problems from LeetCode...")
    problems = fetch_all_free()
    if not problems:
        raise SystemExit("ERROR: không lấy được dữ liệu từ LeetCode API.")

    dataset = build_dataset(problems)
    tag_index = build_tag_index(problems)

    problems_path = DATA_DIR / "problems.json"
    tags_path = DATA_DIR / "tags.json"
    problems_path.write_text(json.dumps(dataset, ensure_ascii=False, indent=2), encoding="utf-8")
    tags_path.write_text(json.dumps(tag_index, ensure_ascii=False, indent=2), encoding="utf-8")

    js_artifact = (
        "/* ============================================================\n"
        "   Knowledge OS — LeetCode Problems Metadata (AUTO-GENERATED)\n"
        f"   Generated by tools/sync_leetcode.py on {dataset['generatedAt']}\n"
        "   KHONG sua tay file nay. Chay lai: python3 tools/sync_leetcode.py\n"
        "   ============================================================ */\n\n"
        f"const LEETCODE_PROBLEMS_META = {json.dumps(dataset, ensure_ascii=False)};\n\n"
        f"const LEETCODE_TAGS_META = {json.dumps(tag_index['tags'], ensure_ascii=False)};\n"
    )
    (WEBSITE_DIR / "leetcode-problems.js").write_text(js_artifact, encoding="utf-8")

    print(f"\nDone: {dataset['totalFree']} free problems, {tag_index['totalTags']} tags")
    print(f"  byDifficulty: {dataset['byDifficulty']}")
    print(f"  -> {problems_path}")
    print(f"  -> {tags_path}")
    print(f"  -> {WEBSITE_DIR / 'leetcode-problems.js'}")


if __name__ == "__main__":
    main()
